apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-keda
spec:
  minReplicaCount: 3
  maxReplicaCount: 100
  pollingInterval: 10
  cooldownPeriod: 600
  idleReplicaCount: 2
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
  - type: memory
    metadata:
      type: Utilization
      value: "60"
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-prod.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      threshold: '50'
      query: sum(rate(http_requests_total{job="my-app",environment="production"}[1m]))
  - type: kubernetes-workload
    metadata:
      podSelector: 'app=my-app'
      value: '10'
  - type: kafka
    metadata:
      bootstrapServers: kafka-prod.example.com:9092
      consumerGroup: my-app-consumer
      topic: my-app-events
      lagThreshold: '100'
  fallback:
    failureThreshold: 5
    replicas: 3
