apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-app-keda
spec:
  minReplicaCount: 1
  maxReplicaCount: 8
  pollingInterval: 15
  cooldownPeriod: 180
  idleReplicaCount: 0
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "60"
  - type: memory
    metadata:
      type: Utilization
      value: "70"
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-stg.monitoring.svc.cluster.local:9090
      metricName: http_requests_per_second
      threshold: '5'
      query: sum(rate(http_requests_total{job="my-app",environment="staging"}[2m]))
  fallback:
    failureThreshold: 2
    replicas: 1
