apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app-stg

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml
- keda-patch.yaml

commonLabels:
  environment: stg
  github.com/nvatuan/domains: "my-app"

namePrefix: stg-
