policies:
  service-high-availability:
    name: Service High Availability
    description: Ensures deployments meeting high availability criteria
    type: opa
    filePath: ha.opa

    enforcement:
      inEffectAfter: 2025-11-11T00:00:00Z
      isWarningAfter: 2026-01-14T00:00:00Z
      isBlockingAfter: 2025-02-14T00:00:00Z

      override:
        comment: "/sp-override-ha"
  
  service-ingress-tls:
    name: Service Ingress TLS
    description: Ensures deployments meeting ingress TLS criteria
    type: opa
    filePath: ingress-tls.opa

    enforcement:
      inEffectAfter: 2025-11-11T00:00:00Z
      isWarningAfter: 2026-01-14T00:00:00Z
      isBlockingAfter: 2025-02-14T00:00:00Z

      override:
        comment: "/sp-override-tls"

integrations:
  mint:
    enabledForServices: []
    disabledForServices: []