apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- keda-scaledobject.yaml

commonLabels:
  app: my-app
  version: v1.0.0
