name: Run GitOps Kustomz

on:
  pull_request:
    paths:
      - 'manifests/services/**'
      - 'policies/**'

permissions:
  contents: read
  pull-requests: write

env:
  KUSTOMIZE_VERSION: '5.3.0'
  OPA_VERSION: '0.60.0'
  GITOPS_KUSTOMZ_VERSION: 'v0.0.1'  # Pin to specific release version
  MANIFESTS_PATH: 'manifests/services'

jobs:
  detect-changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.set-outputs.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Get changed YAML files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E "^${{ env.MANIFESTS_PATH }}/.*\.(yaml|yml)$" || echo "")
          if [ -z "$changed_files" ]; then
            echo "has-files=false" >> $GITHUB_OUTPUT
          else
            echo "has-files=true" >> $GITHUB_OUTPUT
            echo "$changed_files" > changed-files.txt
            echo "Changed files:"
            cat changed-files.txt
          fi

      - name: Detect changed services and environments
        id: set-outputs
        run: |
          # Get list of changed files
          CHANGED_FILES=$(cat changed-files.txt)
          
          # Extract unique service-environment combinations
          # Assumes structure: <manifests_path>/<service>/environments/<env>/
          SERVICES=$(echo "$CHANGED_FILES" | cut -d / -f 3 | sort | uniq | xargs -I@ echo "\"@\"" | tr '\n' ',')
          SERVICES="[${SERVICES::-1}]"
          echo "[DEBUG] SERVICES: $SERVICES"
          
          echo "services=$SERVICES" >> $GITHUB_OUTPUT

  kustomz:
    name: Kustomz on ${{ matrix.service }} (stg,prod)
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.services != '[]'
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.services) }}
      fail-fast: false  # Continue checking all services even if one fails
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Only need base and head commits

      - name: Cache tools
        id: cache-tools
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/bin/kustomize
            /usr/local/bin/opa
            /usr/local/bin/gitops-kustomz
          key: tools-${{ runner.os }}-kustomize-${{ env.KUSTOMIZE_VERSION }}-opa-${{ env.OPA_VERSION }}-gitops-${{ env.GITOPS_KUSTOMZ_VERSION }}

      - name: Install kustomize
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -sL "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${{ env.KUSTOMIZE_VERSION }}/kustomize_v${{ env.KUSTOMIZE_VERSION }}_linux_amd64.tar.gz" | tar xz
          sudo mv kustomize /usr/local/bin/
          kustomize version

      - name: Install OPA
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          curl -L -o opa "https://github.com/open-policy-agent/opa/releases/download/v${{ env.OPA_VERSION }}/opa_linux_amd64_static"
          chmod +x opa
          sudo mv opa /usr/local/bin/
          opa version

      - name: Install gitops-kustomz
        if: steps.cache-tools.outputs.cache-hit != 'true'
        run: |
          # Download pre-built binary from GitHub releases
          ARCH=$(uname -m)
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          
          # Map architecture names
          if [ "$ARCH" = "x86_64" ]; then ARCH="amd64"; fi
          if [ "$ARCH" = "aarch64" ]; then ARCH="arm64"; fi
          
          BINARY_NAME="gitops-kustomz-${OS}-${ARCH}"
          DOWNLOAD_URL="https://github.com/nvatuan/gitops-kustomz/releases/download/${{ env.GITOPS_KUSTOMZ_VERSION }}/${BINARY_NAME}"          

          echo "Downloading ${BINARY_NAME} from ${DOWNLOAD_URL}"
          curl -L "${DOWNLOAD_URL}" -o /usr/local/bin/gitops-kustomz
          chmod +x /usr/local/bin/gitops-kustomz
          /usr/local/bin/gitops-kustomz --version

      - name: Add tools to PATH
        run: |
          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run policy check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gitops-kustomz \
            --run-mode github \
            --gh-repo ${{ github.repository }} \
            --gh-pr-number ${{ github.event.pull_request.number }} \
            --service ${{ matrix.service }} \
            --environments stg,prod \
            --policies-path ./policies \
            --templates-path ./templates
        continue-on-error: false # Binary will only fail if there are misconfigurations. Policy failure doesn't fail the job.
